//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGS.ServerAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalDBContext : DbContext
    {
        public MedicalDBContext()
            : base("name=MedicalDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblClients> tblClients { get; set; }
        public virtual DbSet<tblExperienceAnswers> tblExperienceAnswers { get; set; }
        public virtual DbSet<tblExperienceTypes> tblExperienceTypes { get; set; }
        public virtual DbSet<tblModules> tblModules { get; set; }
        public virtual DbSet<tblQuestions> tblQuestions { get; set; }
        public virtual DbSet<tblReports> tblReports { get; set; }
        public virtual DbSet<tblResult> tblResult { get; set; }
        public virtual DbSet<tblTechExperience> tblTechExperience { get; set; }
        public virtual DbSet<tblUserExperience> tblUserExperience { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
    }
}
