//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGS.ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExperienceTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblExperienceTypes()
        {
            this.tblExperienceAnswers = new HashSet<tblExperienceAnswers>();
            this.tblTechExperience = new HashSet<tblTechExperience>();
            this.tblUserExperience = new HashSet<tblUserExperience>();
        }
    
        public int iExperienceTypeID { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedBy { get; set; }
        public Nullable<int> iEditedBy { get; set; }
        public Nullable<System.DateTime> dtEditedby { get; set; }
        public string strExperienceTitle { get; set; }
        public bool bIsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExperienceAnswers> tblExperienceAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTechExperience> tblTechExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserExperience> tblUserExperience { get; set; }
    }
}
