//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGS.ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestions
    {
        public int iQuestionID { get; set; }
        public string strQuestionID { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedBy { get; set; }
        public Nullable<int> iEditedBy { get; set; }
        public Nullable<System.DateTime> dtEditedby { get; set; }
        public string strQuestion { get; set; }
        public string strFlavourText { get; set; }
        public string strSignificance { get; set; }
        public string strUnit { get; set; }
        public bool bIsDeleted { get; set; }
    }
}
