//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGS.ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReports
    {
        public int iReportID { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedBy { get; set; }
        public Nullable<int> iEditedBy { get; set; }
        public Nullable<System.DateTime> dtEditedby { get; set; }
        public string strReport { get; set; }
        public string strEmail { get; set; }
        public string strContactNumber { get; set; }
        public bool bIsDeleted { get; set; }
    }
}
