//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGS.ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserExperience
    {
        public int iUxID { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedBy { get; set; }
        public Nullable<int> iEditedBy { get; set; }
        public Nullable<System.DateTime> dtEditedby { get; set; }
        public int iExperienceTypeID { get; set; }
        public string strQuestion { get; set; }
        public string strUxQuestionL { get; set; }
        public int iUxQuestionM { get; set; }
        public string strUxQuestionR { get; set; }
        public bool bIsDeleted { get; set; }
    
        public virtual tblExperienceTypes tblExperienceTypes { get; set; }
    }
}
